version: "3.9"

services:
  api: &api
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    container_name: api
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
      - redis
      - rabbitmq
    networks:
      - inv-tracker-network

  db:
    image: postgres:14.5-alpine3.16
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - inv-tracker-dev-db:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - inv-tracker-network

  redis:
    image: redis:alpine3.16
    container_name: inv-tracker-redis
    ports:
      - "6379:6379"
    networks:
      - inv-tracker-network

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'inv-tracker-rabbitmq'
    ports:
        - 5673:5672
        - 15673:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - inv-tracker-network

volumes:
  inv-tracker-dev-db:

networks:
  inv-tracker-network:
    driver: bridge
